### PR TITLE
Fix `get` returning `unknown` for objects that can be `undefined`

### LINKED ISSUE #152: `get` returns `unknown` when the object could be `undefined`
Component:

```typescript
import Component from '@glint/environment-ember-loose/glimmer-component';

interface Foo {
  readonly [key: string]: number | undefined;
}

export default class GlimmerComponent extends Component<{}> {
  public foo?: Foo;
}
```

```hbs
{{test-helper-1 (get this.foo "asd")}}
```

Helper (just to have something that accepts `number | undefined`):

```typescript
import { helper } from '@glint/environment-ember-loose/ember-component/helper';

function testHelper1(params: [number | undefined]): number | undefined {
  return params[0];
}

const testHelper1Helper = helper(testHelper1);

export default testHelper1Helper;

declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry {
    'test-helper-1': typeof testHelper1Helper;
  }
}
```

Instead of compiling, that errs with:

```
app/components/glimmer-component.hbs:1:17 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'number | undefined'.
  Type 'unknown' is not assignable to type 'number'.

1 {{test-helper-1 (get this.foo "asd")}}
                  ~~~~~~~~~~~~~~~~~~~~
```

Replacing `public foo?: Foo` with `public foo!: Foo` makes the error go away.

### PR DESCRIPTION
**Pull request by boris-petrov**
Fixes #152 

I think?

### CODE REVIEW

File: packages/environment-ember-loose/-private/intrinsics/get.d.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import { DirectInvokable, EmptyObject } from '@glint/template/-private/integrati
 import ObjectProxy from '@ember/object/proxy';
 
 export type GetHelper = DirectInvokable<{
-  <T, K extends keyof T>(args: EmptyObject, obj: T, key: K): T[K];
+  <T, K extends keyof T>(args: EmptyObject, obj: T | null | undefined, key: K): T[K];
```
Comment (dfreeman) [inline packages/environment-ember-loose/-private/intrinsics/get.d.ts:5]: Thanks for the PR! I think we need two separate signatures for this, because `{{get maybeString 'length'}}` won't give me a `number` if `maybeString` is undefined.

Probably something like this?
```suggestion
  <T, K extends keyof T>(args: EmptyObject, obj: T, key: K): T[K];
  <T, K extends keyof T>(args: EmptyObject, obj: T | null | undefined, key: K): T[K] | undefined;
```

And then we should update the test accordingly to cover both cases.

Comment (boris-petrov) [reply packages/environment-ember-loose/-private/intrinsics/get.d.ts]: Done, I force-pushed the changes. Thanks for the help!

**Review by dfreeman — APPROVED** [review]
Thank you!
